Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/focal64"

	config.vm.define "minabeS" do |server|
		server.vm.hostname = "minabeS"
		server.vm.network "private_network", ip: "192.168.56.110"
		server.vm.provider "virtualbox" do |v|
			v.name = "minabeS"
			v.memory = 512
			v.cpus = 1
		end

		server.vm.provision "shell", inline: <<-SHELL
			sudo apt-get update
			sudo apt-get install -y curl

			curl -sfL https://get.k3s.io | sh -

			echo "alias k='kubectl'" >> ~/.bashrc
			source ~/.bashrc

			chmod 644 /var/lib/rancher/k3s/server/node-token
		SHELL
	end

	config.vm.define "minabeSW" do |worker|
		worker.vm.hostname = "minabeSW"
		worker.vm.network "private_network", ip: "192.168.56.111"
		worker.vm.provider "virtualbox" do |v|
			v.name = "minabeSW"
			v.memory = 512
			v.cpus = 1
		end

		worker.vm.provision "shell", inline: <<-SHELL
			sudo apt-get update
			sudo apt-get install -y curl

			curl -sfL https://get.k3s.io | K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=$(curl -s http://192.168.56.110/token) sh -
		SHELL
	end
end
